import '../models/chroma_tile.dart';
import '../models/stroke.dart';
import '../models/point.dart';

// vibrant colors matching ColorPalette hex strings
const String colorCanary = '#FFEF00';
const String colorMint = '#98FF98';
const String colorCoral = '#FF7F50';
const String colorIceBlue = '#A1CAF1';
const String colorSilver = '#E5E7EB';

final List<Stroke> welcomeStrokes = [
  const Stroke(
    id: 'w-stroke-1',
    color: '#374151',
    thickness: 3,
    points: [
      Point(x: 25, y: 155),
      Point(x: 60, y: 157),
      Point(x: 120, y: 160),
      Point(x: 180, y: 159),
      Point(x: 255, y: 155),
    ],
  )
];

final List<ChromaTile> initialTiles = [
  // --- GROUP 1: ONBOARDING CLUSTER (Tutorial notes) ---
  ChromaTile(
    id: 'tile-welcome',
    x: -300,
    y: -300,
    width: 280,
    height: 220,
    colorName: 'canary',
    colorHex: colorCanary,
    title: 'Welcome Note',
    content: "Welcome to Scatter!\n\n• Drag from the top header to reposition any note.\n• Left-click and drag inside any note to sketch your ideas.\n• Double-tap or click any note to open the Focused Writing Board.",
    strokes: welcomeStrokes,
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch,
    clusterId: 'onboarding-cluster',
  ),
  ChromaTile(
    id: 'tile-clustering',
    x: 20,
    y: -300,
    width: 280,
    height: 220,
    colorName: 'coral',
    colorHex: colorCoral,
    title: 'Magnetic Grouping 🧲',
    content: "Scatter automatically clusters notes.\n\nPlace any note close to another to create a cluster group.\n\nMoving any member note will slide the entire group together!",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 10,
    clusterId: 'onboarding-cluster',
  ),
  ChromaTile(
    id: 'tile-sketching',
    x: -140,
    y: -40,
    width: 280,
    height: 220,
    colorName: 'canary',
    colorHex: colorCanary,
    title: 'Interactive Sketchpad ✏️',
    content: "Every note is a mini sketchpad!\n\n• Draw or scribble anywhere inside a card body to highlight ideas.\n• Cross out a line of text by sketching a straight horizontal line across it!",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 15,
    clusterId: 'onboarding-cluster',
  ),

  // --- GROUP 2: CAMERA CLUSTER (Canvas controls) ---
  ChromaTile(
    id: 'tile-gestures',
    x: -1250,
    y: 50,
    width: 280,
    height: 220,
    colorName: 'mint',
    colorHex: colorMint,
    title: 'Camera controls',
    content: "Easily navigate your infinite whiteboard canvas:\n\n• Drag any empty background space to pan the camera.\n• Use your mouse scroll wheel to zoom in and out.\n• Use the radial menu at the bottom to reset the view.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 20,
    clusterId: 'camera-cluster',
  ),
  ChromaTile(
    id: 'tile-focus-and-micro',
    x: -930,
    y: 50,
    width: 280,
    height: 220,
    colorName: 'iceBlue',
    colorHex: colorIceBlue,
    title: 'Focus & Micro Notes',
    content: "Tailor notes to your spatial style:\n\n• Click the Minimize (⤢) icon on a card's header to collapse it into a tiny pebble.\n• Click Maximize (⤢) or double-tap to enter the Focused Writing Board.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 30,
    clusterId: 'camera-cluster',
  ),
  ChromaTile(
    id: 'tile-controls-info',
    x: -1090,
    y: 310,
    width: 280,
    height: 200,
    colorName: 'mint',
    colorHex: colorMint,
    title: 'Whiteboard Gizmos ⚙️',
    content: "Need a quick orientation reset?\n\n• Click the center target button in the bottom dial to snap back home.\n• Create new notes instantly in your favorite ink colors using the spawn buttons.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 32,
    clusterId: 'camera-cluster',
  ),

  // --- GROUP 3: NLP SEMANTIC PAIRINGS ---
  ChromaTile(
    id: 'tile-semantic-a',
    x: 450,
    y: -300,
    width: 280,
    height: 220,
    colorName: 'iceBlue',
    colorHex: colorIceBlue,
    title: 'Cosmic Exploration 🌌',
    content: "Scatter features built-in intelligence:\n\n• If you write notes about a shared concept, a bridge is formed.\n• For example, both this note and its partner discuss deep stargazing under a beautiful constellation.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 25,
  ),
  ChromaTile(
    id: 'tile-semantic-b',
    x: 770,
    y: -180,
    width: 280,
    height: 220,
    colorName: 'iceBlue',
    colorHex: colorIceBlue,
    title: 'Stargazing Logs 🔭',
    content: "Observing connections on-the-fly:\n\n• Our NLP semantic parser matches the terms stargazing and constellation.\n• A custom amber-colored glowing bridge is automatically drawn between these cards, tracing your line of thought!",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 27,
  ),

  // --- GROUP 4: SUNKEN & STRUCK THOUGHTS ---
  ChromaTile(
    id: 'tile-sunk-done',
    x: -600,
    y: 500,
    width: 280,
    height: 200,
    colorName: 'coral',
    colorHex: colorCoral,
    title: 'Archived Dream List ⚓',
    content: "This thought is complete.\nEverything on this note has been crossed out!\nIt has sunk into the deep canvas background.",
    strokes: [],
    isArchived: false,
    isSunk: true,
    struckLineIndices: [0, 1, 2],
    createdAt: DateTime.now().millisecondsSinceEpoch + 35,
  ),
  ChromaTile(
    id: 'tile-sunk-info',
    x: -280,
    y: 550,
    width: 280,
    height: 200,
    colorName: 'mint',
    colorHex: colorMint,
    title: 'Sunken Thoughts ⚓',
    content: "Notes can be anchored into the seabed:\n\n• Click the anchor ⚓ button in the header.\n• The note sinks into a low-opacity watermark background.\n• It stays locked so active notes can float or slide directly over it!",
    strokes: [],
    isArchived: false,
    isSunk: true,
    createdAt: DateTime.now().millisecondsSinceEpoch + 37,
  ),

  // --- DEMO MICRO NOTE ---
  ChromaTile(
    id: 'tile-micro-demo',
    x: -800,
    y: 350,
    width: 280,
    height: 200,
    colorName: 'canary',
    colorHex: colorCanary,
    title: 'Idea Capsule 💊',
    content: "A tiny condensed note! Click to reveal or expand.",
    strokes: [],
    isArchived: false,
    isMicro: true,
    createdAt: DateTime.now().millisecondsSinceEpoch + 45,
  ),

  // --- GROUP 5: OFF-SCREEN BEACON GROUP ---
  ChromaTile(
    id: 'tile-offscreen-1',
    x: 1800,
    y: -1200,
    width: 280,
    height: 200,
    colorName: 'coral',
    colorHex: colorCoral,
    title: 'Hidden Vault Part I',
    content: "This group of notes is located far offscreen to demonstrate averaged group beacons.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 40,
    clusterId: 'offscreen-group',
  ),
  ChromaTile(
    id: 'tile-offscreen-2',
    x: 2100,
    y: -1200,
    width: 280,
    height: 200,
    colorName: 'coral',
    colorHex: colorCoral,
    title: 'Hidden Vault Part II',
    content: "Notice that instead of drawing three individual beacons, Scatter averages them into a single group beacon on the screen edge.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 42,
    clusterId: 'offscreen-group',
  ),
  ChromaTile(
    id: 'tile-offscreen-3',
    x: 1950,
    y: -950,
    width: 280,
    height: 200,
    colorName: 'canary',
    colorHex: colorCanary,
    title: 'Hidden Vault Part III',
    content: "Following the beacon will navigate you straight to this hidden cluster of notes.",
    strokes: [],
    isArchived: false,
    createdAt: DateTime.now().millisecondsSinceEpoch + 44,
    clusterId: 'offscreen-group',
  ),
];
